services:
  api:
    image: api
    build:
      context: .
      dockerfile: TaskManagementSystem.API/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - "postgres"
    networks:
      - tsm
  
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    networks:
      - tsm

volumes:
  postgres_data:

networks:
  tsm:
    driver: bridge
