services:
  taskmanagementsystem.api:
    image: taskmanagementsystem.api
    build:
      context: .
      dockerfile: TaskManagementSystem.API/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - "postgres"
    networks:
      - tsm
    
  taskmanagementsystem.client:
    image: taskmanagementsystem.client
    build:
      context: .
      dockerfile: TaskManagementSystem.Client/Dockerfile
  
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    networks:
      - tsm

volumes:
  postgres_data:
    
networks:
  tsm:
    driver: bridge
